
import React, { useRef } from 'react';
import { Printer, X, FileDown, Image as ImageIcon, MessageCircle } from 'lucide-react';
import html2pdf from 'html2pdf.js';
import html2canvas from 'html2canvas';
import { formatBanglaCurrency, toBanglaNumerals } from '../lib/utils';

export type DocType = 'ledger' | 'damage' | 'invoice' | 'demand' | 'purchase' | 'pnl' | 'stock';

interface UniversalPrintModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  type: DocType;
  data: any;
  compName: string;
  compAddress: string;
}

export default function UniversalPrintModal({ 
  isOpen, 
  onClose, 
  title, 
  type, 
  data, 
  compName, 
  compAddress 
}: UniversalPrintModalProps) {
  const printRef = useRef<HTMLDivElement>(null);

  if (!isOpen) return null;

  const handleDownloadPDF = () => {
    if (!printRef.current) return;
    
    const element = printRef.current;
    const opt = {
      margin: [10, 10, 10, 10] as [number, number, number, number],
      filename: `${type}_${new Date().toISOString().split('T')[0]}.pdf`,
      image: { type: 'jpeg' as const, quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true, logging: false },
      jsPDF: { unit: 'mm' as const, format: 'a4' as const, orientation: 'portrait' as const }
    };

    html2pdf().set(opt).from(element).save();
  };

  const handleDownloadJPG = async () => {
    if (!printRef.current) return;
    
    const canvas = await html2canvas(printRef.current, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff'
    });
    
    const link = document.createElement('a');
    link.download = `${type}_${new Date().toISOString().split('T')[0]}.jpg`;
    link.href = canvas.toDataURL('image/jpeg', 0.9);
    link.click();
  };

  const handleShareWhatsApp = () => {
    let message = `*${compName}*\n${compAddress}\n\n`;
    message += `*${title}*\n`;
    message += `তারিখ: ${new Date().toLocaleDateString()}\n\n`;

    if (type === 'ledger') {
      message += `কোম্পানি: ${data.companyName}\n`;
      message += `বর্তমান ব্যালেন্স: ${formatBanglaCurrency(data.balance)}\n`;
      message += `অবস্থা: ${data.balance >= 0 ? 'দেনা (Payable)' : 'পাওনা (Receivable)'}\n`;
    } else if (type === 'invoice') {
      message += `ইনভয়েস নং: ${data.invoiceNo}\n`;
      message += `কাস্টমার: ${data.customerName}\n`;
      message += `মোট বিল: ${formatBanglaCurrency(data.totalAmount)}\n`;
    }
    // Add more types as needed

    message += `\n_Generated by Fast-Entry POS_`;
    
    const encodedMessage = encodeURIComponent(message);
    window.open(`https://wa.me/?text=${encodedMessage}`, '_blank');
  };

  const renderContent = () => {
    switch (type) {
      case 'ledger':
        return (
          <div className="space-y-6">
            <div className="flex justify-between items-start border-b border-slate-200 pb-4">
              <div>
                <p className="text-xs text-slate-500 uppercase font-bold tracking-wider">সাপ্লায়ার কোম্পানি</p>
                <h3 className="text-xl font-black text-slate-900">{data.companyName}</h3>
                <p className="text-sm font-bold text-slate-600">আইডি: {data.companyId}</p>
              </div>
              <div className="text-right">
                <p className="text-xs text-slate-500 uppercase font-bold tracking-wider">বর্তমান স্থিতি</p>
                <h3 className={`text-xl font-black font-mono ${data.balance >= 0 ? 'text-rose-600' : 'text-emerald-600'}`}>
                  {formatBanglaCurrency(Math.abs(data.balance))}
                </h3>
                <p className="text-[10px] font-bold text-slate-400">
                  {data.balance >= 0 ? 'দেনা (Payable)' : 'পাওনা (Receivable)'}
                </p>
              </div>
            </div>

            <table className="w-full text-[12px] border-collapse">
              <thead>
                <tr className="bg-slate-100 border-y border-slate-200 text-slate-600">
                  <th className="py-2 px-2 text-left">তারিখ</th>
                  <th className="py-2 px-2 text-left">বিবরণ/ভাউচার</th>
                  <th className="py-2 px-2 text-right">ডেবিট (পরিশোধ)</th>
                  <th className="py-2 px-2 text-right">ক্রেডিট (পারচেজ)</th>
                  <th className="py-2 px-2 text-right">জের (Balance)</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {data.entries.map((entry: any, idx: number) => (
                  <tr key={idx}>
                    <td className="py-2 px-2 font-mono">{entry.date}</td>
                    <td className="py-2 px-2">
                      <span className="font-bold">{entry.type === 'Purchase' ? 'পারচেজ' : entry.type === 'Payment' ? 'পেমেন্ট' : entry.type}</span>
                      <p className="text-[10px] text-slate-400 italic">{entry.remarks}</p>
                    </td>
                    <td className="py-2 px-2 text-right font-mono">{entry.debit > 0 ? formatBanglaCurrency(entry.debit) : '—'}</td>
                    <td className="py-2 px-2 text-right font-mono">{entry.credit > 0 ? formatBanglaCurrency(entry.credit) : '—'}</td>
                    <td className="py-2 px-2 text-right font-mono font-bold">{formatBanglaCurrency(entry.balance)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        );
      case 'invoice':
        return (
          <div className="space-y-6">
            <div className="flex justify-between items-start border-b border-slate-200 pb-4">
              <div>
                <p className="text-xs text-slate-500 uppercase font-bold tracking-wider">গ্রাহক / দোকান</p>
                <h3 className="text-xl font-black text-slate-900">{data.customerName}</h3>
                <p className="text-sm font-bold text-slate-600">ডিএসআর: {data.dsrName || '—'} • রুট: {data.routeName || '—'}</p>
              </div>
              <div className="text-right">
                <p className="text-xs text-slate-500 uppercase font-bold tracking-wider">মেমো নম্বর</p>
                <h3 className="text-xl font-black font-mono">#{data.invoiceNo}</h3>
                <p className="text-[10px] font-bold text-slate-400">তারিখ: {data.date}</p>
              </div>
            </div>

            <table className="w-full text-[11px] border-collapse border border-slate-200">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200 text-slate-600">
                  <th className="py-2 px-2 text-left border-r border-slate-200">আইটেম বিবরণ</th>
                  <th className="py-2 px-2 text-center border-r border-slate-200">চালুকৃত (পিস)</th>
                  <th className="py-2 px-2 text-center border-r border-slate-200">ফেরত (পিস)</th>
                  <th className="py-2 px-2 text-center border-r border-slate-200">বিক্রি (পিস)</th>
                  <th className="py-2 px-2 text-right border-r border-slate-200">একক দর</th>
                  <th className="py-2 px-2 text-right">মোট টাকা</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200">
                {data.items.map((item: any, idx: number) => (
                  <tr key={idx}>
                    <td className="py-2 px-2 font-bold border-r border-slate-200">{item.productName}</td>
                    <td className="py-2 px-2 text-center font-mono border-r border-slate-200">{item.qty || 0}</td>
                    <td className="py-2 px-2 text-center font-mono border-r border-slate-200 text-rose-600">{item.returnedQty || 0}</td>
                    <td className="py-2 px-2 text-center font-mono border-r border-slate-200 font-black">{item.soldQty || item.qty}</td>
                    <td className="py-2 px-2 text-right font-mono border-r border-slate-200">{formatBanglaCurrency(item.rate)}</td>
                    <td className="py-2 px-2 text-right font-mono font-bold">{formatBanglaCurrency((item.soldQty || item.qty) * item.rate)}</td>
                  </tr>
                ))}
              </tbody>
              <tfoot className="border-t-2 border-slate-900 bg-slate-50">
                <tr>
                  <td colSpan={5} className="py-2 px-2 text-right font-bold">মোট বিক্রয় মূল্য (Gross Total):</td>
                  <td className="py-2 px-2 text-right font-mono font-black">{formatBanglaCurrency(data.subtotal)}</td>
                </tr>
                {data.discount > 0 && (
                  <tr>
                    <td colSpan={5} className="py-2 px-2 text-right font-bold text-rose-500">ডিসকাউন্ট ছাড় (-):</td>
                    <td className="py-2 px-2 text-right font-mono font-bold text-rose-500">{formatBanglaCurrency(data.discount)}</td>
                  </tr>
                )}
                <tr className="bg-slate-900 text-white">
                  <td colSpan={5} className="py-3 px-2 text-right font-black">নিট আদায়যোগ্য বিল (Net Total):</td>
                  <td className="py-3 px-2 text-right font-mono font-black text-lg">{formatBanglaCurrency(data.netTotal)}</td>
                </tr>
                <tr>
                  <td colSpan={5} className="py-2 px-2 text-right font-bold text-emerald-700">নগদ প্রদান (Cash Paid):</td>
                  <td className="py-2 px-2 text-right font-mono font-bold text-emerald-700">{formatBanglaCurrency(data.cashPaid)}</td>
                </tr>
                <tr>
                  <td colSpan={5} className="py-2 px-2 text-right font-bold text-amber-700">অবশিষ্ট বকেয়া (Due):</td>
                  <td className="py-2 px-2 text-right font-mono font-black text-amber-700">{formatBanglaCurrency(data.dueAmount)}</td>
                </tr>
              </tfoot>
            </table>
          </div>
        );
      case 'damage':
        return (
          <div className="space-y-6">
            <div className="flex justify-between border-b border-slate-200 pb-4">
              <div>
                <p className="text-xs text-slate-500 uppercase font-bold tracking-wider">কোম্পানি</p>
                <h3 className="text-lg font-black">{data.companyName}</h3>
              </div>
              <div className="text-right">
                <p className="text-xs text-slate-500 uppercase font-bold tracking-wider">স্লিপ নং</p>
                <h3 className="text-lg font-black font-mono">#{data.id}</h3>
              </div>
            </div>
            <table className="w-full text-base border-collapse border border-slate-200">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200">
                  <th className="p-3 text-left">আইটেম</th>
                  <th className="p-3 text-center">পরিমাণ</th>
                  <th className="p-3 text-right">মূল্য (৳)</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="p-3 font-bold">{data.productName}</td>
                  <td className="p-3 text-center font-mono">{data.qty} পিস</td>
                  <td className="p-3 text-right font-mono font-black">{formatBanglaCurrency(data.value)}</td>
                </tr>
              </tbody>
            </table>
            <div className="bg-slate-50 p-4 rounded-xl">
              <p className="text-xs font-bold text-slate-500 uppercase mb-1">মন্তব্য (Remarks):</p>
              <p className="text-sm italic">{data.remarks || 'কোনো মন্তব্য নেই'}</p>
            </div>
          </div>
        );
      case 'demand':
        return (
          <div className="space-y-6">
            <div className="flex justify-between border-b border-slate-200 pb-4">
              <div>
                <p className="text-xs text-slate-500 uppercase font-bold tracking-wider">কোম্পানি</p>
                <h3 className="text-lg font-black">{data.companyName}</h3>
              </div>
              <div className="text-right">
                <p className="text-xs text-slate-500 uppercase font-bold tracking-wider">ডিমান্ড তারিখ</p>
                <h3 className="text-lg font-black font-mono">{data.date}</h3>
              </div>
            </div>
            <table className="w-full text-base border-collapse border border-slate-200">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200">
                  <th className="p-3 text-left">আইটেম</th>
                  <th className="p-3 text-center">পরিমাণ (পিস)</th>
                  <th className="p-3 text-center">কার্টুন (Carton)</th>
                </tr>
              </thead>
              <tbody>
                {data.items.map((item: any, idx: number) => (
                  <tr key={idx} className="border-b border-slate-100">
                    <td className="p-3 font-bold">{item.productName}</td>
                    <td className="p-3 text-center font-mono">{item.qty}</td>
                    <td className="p-3 text-center font-mono">{item.cartons}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        );
      case 'stock':
        return (
          <div className="space-y-6">
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 flex justify-between items-center">
              <div>
                <p className="text-xs text-slate-500 uppercase font-bold tracking-wider">রিপোর্ট ধরন</p>
                <h3 className="text-lg font-black text-slate-900">স্টক ইনভেন্টরি ও মালামাল রিপোর্ট</h3>
              </div>
              <div className="text-right">
                <p className="text-xs text-slate-500 uppercase font-bold tracking-wider">মোট স্টক ভ্যালু</p>
                <h3 className="text-xl font-black text-indigo-600 font-mono">{formatBanglaCurrency(data.totalValue)}</h3>
              </div>
            </div>

            <table className="w-full text-[10px] border-collapse border border-slate-200">
              <thead>
                <tr className="bg-slate-100 border-b border-slate-200 text-slate-600">
                  <th className="py-2 px-2 text-left border-r border-slate-200">পণ্যের নাম</th>
                  <th className="py-2 px-2 text-center border-r border-slate-200">প্রারম্ভিক স্টক</th>
                  <th className="py-2 px-2 text-center border-r border-slate-200">প্রাপ্তি (+)</th>
                  <th className="py-2 px-2 text-center border-r border-slate-200">বিক্রি (-)</th>
                  <th className="py-2 px-2 text-center border-r border-slate-200">বর্তমান স্টক (পিস)</th>
                  <th className="py-2 px-2 text-right border-r border-slate-200">একক মূল্য</th>
                  <th className="py-2 px-2 text-right">মোট মূল্য (৳)</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200">
                {data.items.map((item: any, idx: number) => (
                  <tr key={idx} className={item.currentStock <= (item.minStock || 5) ? 'bg-rose-50' : ''}>
                    <td className="py-2 px-2 font-bold border-r border-slate-200">{item.name}</td>
                    <td className="py-2 px-2 text-center font-mono border-r border-slate-200">{item.openingStock || 0}</td>
                    <td className="py-2 px-2 text-center font-mono border-r border-slate-200 text-emerald-600">+{item.received || 0}</td>
                    <td className="py-2 px-2 text-center font-mono border-r border-slate-200 text-rose-600">-{item.sold || 0}</td>
                    <td className="py-2 px-2 text-center font-mono border-r border-slate-200 font-black">{item.currentStock}</td>
                    <td className="py-2 px-2 text-right font-mono border-r border-slate-200">{formatBanglaCurrency(item.costPrice || item.price)}</td>
                    <td className="py-2 px-2 text-right font-mono font-bold">{formatBanglaCurrency(item.currentStock * (item.costPrice || item.price))}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        );
      case 'pnl':
        return (
          <div className="space-y-6">
            <table className="w-full text-base border-collapse">
              <tbody>
                <tr>
                  <td className="py-3 border-b border-slate-200 font-bold">(+) মোট ইনভয়েস বিক্রয় (Gross Sales)</td>
                  <td className="py-3 border-b border-slate-200 text-right font-mono font-black">{formatBanglaCurrency(data.totalGrossSales)}</td>
                </tr>
                <tr>
                  <td className="py-3 border-b border-slate-200 font-bold text-slate-500">(-) বিক্রয় ফেরত ও ড্যামেজ ছাড় (Damage & Sales Returns)</td>
                  <td className="py-3 border-b border-slate-200 text-right font-mono text-slate-500">- {formatBanglaCurrency(data.totalSalesReturns)}</td>
                </tr>
                <tr className="bg-slate-50">
                  <td className="py-3 px-3 font-black text-indigo-900 border-l-4 border-indigo-500">= নিট বিক্রয় আয় (Net Sales Revenue)</td>
                  <td className="py-3 px-3 text-right font-mono font-black text-indigo-900">{formatBanglaCurrency(data.totalNetSales)}</td>
                </tr>
                <tr>
                  <td className="py-3 border-b border-slate-200 font-bold text-slate-500">(-) বিক্রিত পণ্যের মূল ক্রয়মূল্য (COGS)</td>
                  <td className="py-3 border-b border-slate-200 text-right font-mono text-slate-500">- {formatBanglaCurrency(data.totalCOGS)}</td>
                </tr>
                <tr className="bg-emerald-50">
                  <td className="py-3 px-3 font-black text-emerald-900 border-l-4 border-emerald-500">= পণ্য বিক্রির নিট লাভ (Gross Profit)</td>
                  <td className="py-3 px-3 text-right font-mono font-black text-emerald-900">{formatBanglaCurrency(data.grossProfit)}</td>
                </tr>
                <tr>
                  <td className="py-3 border-b border-slate-200 font-bold text-emerald-700">(+) কোম্পানি ইনসেন্টিভ ও ক্লেইম জমা (Incentive & Claims)</td>
                  <td className="py-3 border-b border-slate-200 text-right font-mono font-black text-emerald-700">+ {formatBanglaCurrency(data.totalIncentiveIncome)}</td>
                </tr>
                <tr>
                  <td className="py-6 font-black text-lg underline decoration-slate-200" colSpan={2}>পরিচালন খরচ (Operating Expenses):</td>
                </tr>
                {/* Simplified expense rendering for space */}
                <tr>
                  <td className="py-2 pl-6 text-slate-600 font-medium">মোট পরিচালন খরচ (Total Operating Expenses)</td>
                  <td className="py-2 text-right font-mono text-slate-600">{formatBanglaCurrency(data.totalOperatingExpenses)}</td>
                </tr>
                <tr className="border-t-2 border-slate-900 border-b-4 mt-4 bg-slate-900 text-white">
                  <td className="py-5 px-4 text-xl font-black uppercase tracking-tight">চূড়ান্ত নিট লাভ / ক্ষতি (NET PROFIT)</td>
                  <td className="py-5 px-4 text-right font-mono text-2xl font-black">{formatBanglaCurrency(data.netOperatingProfit)}</td>
                </tr>
              </tbody>
            </table>
          </div>
        );
      default:
        return <div className="py-20 text-center text-slate-400">Template for {type} is coming soon.</div>;
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4 md:p-8 overflow-hidden print:hidden">
      <div className="bg-white w-full max-w-5xl max-h-full flex flex-col rounded-2xl shadow-2xl overflow-hidden animate-in fade-in zoom-in duration-300">
        {/* Modal Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 bg-slate-50/50">
          <div className="flex items-center gap-2">
            <Printer className="h-5 w-5 text-indigo-600" />
            <h2 className="font-sans font-black text-slate-900">{title} - প্রিভিউ</h2>
          </div>
          <div className="flex items-center gap-2 flex-wrap justify-end">
            <button
              onClick={handleShareWhatsApp}
              className="flex items-center gap-2 rounded-lg bg-emerald-500 text-white hover:bg-emerald-600 py-2 px-3 text-[10px] font-bold shadow-sm transition"
            >
              <MessageCircle className="h-4 w-4" /> হোয়াটসঅ্যাপে পাঠান
            </button>
            <button
              onClick={handleDownloadJPG}
              className="flex items-center gap-2 rounded-lg bg-blue-600 text-white hover:bg-blue-700 py-2 px-3 text-[10px] font-bold shadow-sm transition"
            >
              <ImageIcon className="h-4 w-4" /> ডাউনলোড JPG
            </button>
            <button
              onClick={handleDownloadPDF}
              className="flex items-center gap-2 rounded-lg bg-slate-700 text-white hover:bg-slate-800 py-2 px-3 text-[10px] font-bold shadow-sm transition"
            >
              <FileDown className="h-4 w-4" /> ডাউনলোড PDF
            </button>
            <button
              onClick={() => window.print()}
              className="flex items-center gap-2 rounded-lg bg-slate-900 text-white hover:bg-slate-800 py-2 px-3 text-[10px] font-bold shadow-sm transition"
            >
              <Printer className="h-4 w-4" /> প্রিন্ট
            </button>
            <button
              onClick={onClose}
              className="flex items-center justify-center h-8 w-8 rounded-full bg-white border border-slate-200 text-slate-500 hover:bg-slate-50 hover:text-slate-900 transition"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        {/* Modal Content - Scrollable */}
        <div className="flex-1 overflow-y-auto p-8 bg-slate-200/30 flex justify-center">
          <div 
            ref={printRef}
            className="bg-white w-[210mm] min-h-[297mm] p-[15mm] shadow-lg font-sans text-slate-900"
            style={{ height: 'fit-content' }}
          >
            {/* Business Header */}
            <div className="text-center pb-6 border-b-2 border-slate-900 mb-8">
              <h1 className="text-3xl font-black tracking-tight uppercase">{compName}</h1>
              <p className="text-sm font-bold text-slate-600 mt-1">{compAddress}</p>
              <h2 className="text-xl font-bold mt-6 underline underline-offset-8 decoration-slate-300">{title}</h2>
              <p className="text-[10px] text-slate-400 mt-3 font-mono">জেনারেট সময়: {new Date().toLocaleString()}</p>
            </div>

            {/* Document Content */}
            {renderContent()}

            {/* Footer Signatures */}
            <div className="mt-24 grid grid-cols-3 gap-12 text-center text-[10px] font-bold uppercase tracking-wider text-slate-400">
              <div className="border-t border-slate-200 pt-2">প্রস্তুতকারক</div>
              <div className="border-t border-slate-200 pt-2">হিসাবরক্ষক</div>
              <div className="border-t border-slate-200 pt-2">স্বত্বাধিকারী/ম্যানেজার</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
